version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    working_directory: ~/scheduler
    steps:
      - checkout
      - run:
        name: Run Build
        command: ./gradlew build

workflows:
  version: 2
  build:
    jobs:
      - build